name: Infra Provisioning through Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (e.g., dev, staging, prod)"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - staging
        - prod

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: read
  pull-requests: write   
  id-token: write  

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::302263075199:role/OIDC-Terraform
          role-session-name: githubactions
          aws-region: "us-west-2"     

      - name: Install TFLint
        run: |
          TFLINT_VERSION="v0.55.0"
          curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
          
          if [ ! -s "tflint.zip" ]; then
            echo "Error: Downloaded TFLint archive is empty or invalid."
            exit 1
          fi

          unzip tflint.zip
          chmod +x tflint
          sudo mv tflint /usr/local/bin/
          rm tflint.zip
          
          echo "TFLint installed successfully:"
          tflint --version

      # Step: Run TFLint
      - name: Run TFLint
        continue-on-error: true
        run: |
          cd ./Infra
          # Ensure .tflint.hcl exists
          if [ ! -f ".tflint.hcl" ]; then
            cat <<EOF > .tflint.hcl
            plugin "terraform" {
              enabled = true
            }
            rule "aws_dynamodb_table_tag" {
              enabled = true
              message = "DynamoDB tables should have tags."
              resource_type = "aws_dynamodb_table"
              attribute = "tags"
              condition = "notempty"
            }
            rule "aws_lambda_function_environment" {
              enabled = true
              message = "Lambda functions should have environment variables."
              resource_type = "aws_lambda_function"
              attribute = "environment"
              condition = "notempty"
            }
            rule "aws_api_gateway_stage_logging" {
              enabled = true
              message = "API Gateway stages should have logging enabled."
              resource_type = "aws_api_gateway_stage"
              attribute = "access_log_settings"
              condition = "notempty"
            }
EOF
          fi

          # Install TFLint plugin (Terraform)
          tflint --init

          # Run TFLint with proper syntax
          tflint --config .tflint.hcl

      # Step: Install Checkov
      - name: Install Checkov
        run: |
          pip install checkov
          checkov --version

      # Step: Create Checkov Configuration
      - name: Create Checkov Configuration
        run: |
          cd ./Infra
          cat <<EOF > .checkov.yaml
          policies:
            - id: CKV_AWS_2
              name: "Ensure DynamoDB tables have encryption enabled"
              category: "DynamoDB"
              severity: "MEDIUM"
              resource_types:
                - "aws_dynamodb_table"
              checks:
                - "server_side_encryption.enabled == true"
            - id: CKV_AWS_3
              name: "Ensure Lambda functions have logging enabled"
              category: "Lambda"
              severity: "LOW"
              resource_types:
                - "aws_lambda_function"
              checks:
                - "logging_configuration.enabled == true"
            - id: CKV_AWS_4
              name: "Ensure API Gateway stages have logging enabled"
              category: "API Gateway"
              severity: "LOW"
              resource_types:
                - "aws_api_gateway_stage"
              checks:
                - "access_log_settings.enabled == true"
EOF

      # Step: Run Checkov Security Scan
      - name: Run Checkov
        continue-on-error: true
        run: |
          cd ./Infra
          checkov --directory . --config-file .checkov.yaml
          
      # Step: Terraform Init
      - name: Terraform Init
        run: | 
          cd ./Infra
          terraform init

      # Step: Run Terraform Validate (validate configuration files)
      - name: Terraform Validate
        run: |
          cd ./Infra
          terraform validate

      # Step: Terraform Workspace Select or Create
      - name: Terraform Workspace Select or Create
        run: |
          cd ./Infra
          terraform workspace select ${{ github.event.inputs.environment || 'dev' }} || terraform workspace new ${{ github.event.inputs.environment || 'dev' }}

      # Step: Terraform Plan
      - name: Terraform Plan
        run: |
          cd ./Infra
          terraform plan -out=tfplan

      # Step: Checkout Repository for PR
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }} 
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step: Configure Git for committing generated README.md
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step: Generate Markdown with Terraform Docs
      - name: Generate Markdown with Terraform Docs
        if: ${{ github.event_name == 'pull_request' }}
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: ./Infra
          output-file: README.md
          output-method: inject
          git-push: true
          config-file: .terraform-docs.yml

      # Step: Add README.md to PR Comment using Sticky Comment
      - name: Post README.md as PR Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          header: "Terraform Documentation 📖"
          path: "./Infra/README.md"
    
      # Step: Apply Terraform if PR is merged
      - name: Apply Terraform on Merge the PR
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          cd ./Infra
          terraform init
          terraform apply -auto-approve
